server:
  port: 8062
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: OTQxNmFiNTYyODI0ZjU0M2JmM2YzYzUzYjczZWFmZWM5YzRmZWVjYjBlMzU0MWU5YTRlNjg2MDEwNGYwYmJmODUzM2ExMjU3NGE2Mzg3ODc2ZDg5NTU1MTVjMGI2Y2RjMmMyMDBiN2ZlMDI2ODkyZDliYmU3Y2ZkMmZlZGEzZWY=
        # Token is valid 24 hours
        token-validity-in-seconds: 300
        token-validity-in-seconds-for-refresh-token: 2592000
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:mysql://localhost:3306/flexitrade
    driverClassName: com.mysql.cj.jdbc.Driver
    username: flexitrade
    password: flexitrade
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
#  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
#    contexts: dev
  mail:
    host: localhost
    port: 25
    username:
    password:
#  messages:
#    cache-duration: PT1S # 1 second, see the ISO 8601 standard
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/flexitrade
#    username: flexitrade
#    password: flexitrade
   
springdoc:
  swagger-ui:
    urls:
      - name: employee
        url: /v3/api-docs/employee
      - name: department
        url: /v3/api-docs/department
      - name: organization
        url: /v3/api-docs/organization